

//爬取分类
export const CRAWLING_LS_CREATE = 'CRAWLING_LS_CREATE'
export const CRAWLING_LS_CREATE_FULFILLED = `${CRAWLING_LS_CREATE}_FULFILLED`


//爬取最近更新的分类
export const CRAWLING_LS_CREATE_UPDATE = 'CRAWLING_LS_CREATE_UPDATE'
export const CRAWLING_LS_CREATE_UPDATE_FULFILLED = `${CRAWLING_LS_CREATE_UPDATE}_FULFILLED`


//删除所有分类
export const CRAWLING_ALL_DELTE = 'CRAWLING_ALL_DELTE'
export const CRAWLING_ALL_DELTE_FULFILLED = `${CRAWLING_ALL_DELTE}_FULFILLED`


//爬取分类数据  这个接口 某个分类存在多条数据  page 起码要同步到10
export const CRAWLING_LS_LIST_CREATE = 'CRAWLING_LS_LIST_CREATE'
export const CRAWLING_LS_LIST_CREATE_FULFILLED = `${CRAWLING_LS_LIST_CREATE}_FULFILLED`


//爬取首页所有热门网站
export const CRAWLING_NAV_CREATE = 'CRAWLING_NAV_CREATE'
export const CRAWLING_NAV_CREATE_FULFILLED = `${CRAWLING_NAV_CREATE}_FULFILLED`


//爬取在线工具
export const CRAWLING_TOOLS_CREATE = 'CRAWLING_TOOLS_CREATE'
export const CRAWLING_TOOLS_CREATE_FULFILLED = `${CRAWLING_TOOLS_CREATE}_FULFILLED`


